import {
  authenticateForSite,
  commitSecretUpdateForSite,
  prepareSecretUpdateForSite,
  registerForSite,
} from '../shared/upspaActions';
import { getConfig } from '../shared/config';

type UpSpaFlow = 'register' | 'auth' | 'secret-update';

const bypassForms = new WeakSet<HTMLFormElement>();

function getPasswordInputs(form: HTMLFormElement): HTMLInputElement[] {
  return Array.from(form.querySelectorAll('input[type="password"]'));
}

function getInputByNames(form: HTMLFormElement, names: string[]): HTMLInputElement | null {
  for (const name of names) {
    const el = form.querySelector(`input[name="${name}"]`);
    if (el instanceof HTMLInputElement) return el;
  }
  return null;
}

function setInputValue(input: HTMLInputElement, value: string): void {
  const setter = Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value')?.set;
  setter?.call(input, value);

  input.dispatchEvent(new Event('input', { bubbles: true }));
  input.dispatchEvent(new Event('change', { bubbles: true }));
}

function getAccountId(form: HTMLFormElement): string {
  const accountInput = getInputByNames(form, [
    'account_id',
    'uid_prime',
    'uidp',
    'username',
    'email',
    'login',
  ]);

  return accountInput?.value.trim() || '';
}

function getMainUid(form: HTMLFormElement): string | undefined {
  const uidInput = getInputByNames(form, [
    'uid',
    'upspa_uid',
    'main_uid',
    'setup_uid',
  ]);

  if (!uidInput) return undefined;

  const uid = uidInput.value.trim();
  if (!uid) throw new Error('Main UpSPA UID is empty.');
  return uid;
}

async function fillMainUidInputs(): Promise<void> {
  const cfg = await getConfig();
  const uid = cfg.uid?.trim();
  if (!uid) return;

  const inputs = document.querySelectorAll<HTMLInputElement>(
    'input[name="uid"], input[name="upspa_uid"], input[name="main_uid"], input[name="setup_uid"]',
  );

  inputs.forEach((input) => {
    if (!input.value.trim()) setInputValue(input, uid);
  });
}

function explainError(e: unknown): string {
  const msg = e instanceof Error ? e.message : String(e);

  if (msg.toLowerCase().includes('aead error')) {
    return [
      'Could not decrypt the UpSPA setup/record.',
      'Check that Main UpSPA UID matches the UID used in Options setup, the master password is correct, and the SP databases were not reset without running setup/provision again.',
    ].join(' ');
  }

  return msg;
}

function makeLsj(form: HTMLFormElement): string {
  const accountId = getAccountId(form);

  // Important:
  // origin alone gives one UpSPA record per website.
  // origin|account_id gives one UpSPA record per website account.
  return accountId ? `${window.location.origin}|${accountId}` : window.location.origin;
}

function detectFlow(form: HTMLFormElement, pwds: HTMLInputElement[]): UpSpaFlow | null {
  const explicit = form.getAttribute('data-upspa-flow');

  if (explicit === 'register' || explicit === 'auth' || explicit === 'secret-update') {
    return explicit;
  }

  const action = form.getAttribute('action') || '';

  if (action.includes('secret-update')) return 'secret-update';
  if (action.includes('register')) return 'register';
  if (action.includes('login')) return 'auth';

  if (pwds.length === 1) return 'auth';
  if (pwds.length === 2) return 'register';
  if (pwds.length >= 3) return 'secret-update';

  return null;
}
function submitNative(form: HTMLFormElement): void {
  bypassForms.add(form);
  HTMLFormElement.prototype.submit.call(form);
}

async function handleRegister(form: HTMLFormElement, pwds: HTMLInputElement[]): Promise<void> {
  if (pwds.length < 1) throw new Error('Registration form has no password field.');

  const password = pwds[0].value;

  if (pwds.length >= 2 && pwds[0].value !== pwds[1].value) {
    throw new Error('Registration password fields do not match.');
  }

  const transformed = await registerForSite(makeLsj(form), password, getMainUid(form));

  // Fill every password field with the LS password generated by UpSPA.
  for (const pwd of pwds) {
    setInputValue(pwd, transformed);
  }

  submitNative(form);
}

async function handleAuth(form: HTMLFormElement, pwds: HTMLInputElement[]): Promise<void> {
  if (pwds.length < 1) throw new Error('Login form has no password field.');

  const masterPassword = pwds[0].value;
  const transformed = await authenticateForSite(makeLsj(form), masterPassword, getMainUid(form));

  setInputValue(pwds[0], transformed);
  submitNative(form);
}

async function handleSecretUpdate(
  form: HTMLFormElement,
  pwds: HTMLInputElement[],
): Promise<void> {
  console.log('[UpSPA] secret update flow detected');

  const lsj = makeLsj(form);
  const mainUid = getMainUid(form);
  console.log('[UpSPA] lsj =', lsj);
  console.log('[UpSPA] uid =', mainUid ?? '(config)');

  const masterInput =
    getInputByNames(form, ['upspa_master_password', 'master_password']) ?? pwds[0];

  if (!masterInput) {
    throw new Error('Secret-update form has no UpSPA master password field.');
  }

  if (!masterInput.value) {
    throw new Error('Master password is empty.');
  }

  const prepared = await prepareSecretUpdateForSite(lsj, masterInput.value, mainUid);

  console.log('[UpSPA] oldForLs length =', prepared.oldForLs.length);
  console.log('[UpSPA] newForLs length =', prepared.newForLs.length);

  if (!prepared.oldForLs || !prepared.newForLs) {
    throw new Error('Secret-update generated empty old/new LS secret.');
  }

  const formData = new FormData(form);

  // Remove human master password. The LS must never receive it.
  formData.delete('upspa_master_password');
  formData.delete('master_password');

  // Force the LS old/new password fields.
  formData.set('old_password', prepared.oldForLs);
  formData.set('new_password', prepared.newForLs);

  // If the demo LS has confirm field later, keep it consistent.
  formData.set('new_password_confirm', prepared.newForLs);

  const body = new URLSearchParams();
  formData.forEach((value, key) => {
    body.set(key, String(value));
  });

  const action = form.getAttribute('action') || window.location.href;
  const actionUrl = new URL(action, window.location.href).toString();
  const method = (form.getAttribute('method') || 'POST').toUpperCase();

  console.log('[UpSPA] submitting secret-update via fetch');
  console.log('[UpSPA] action =', actionUrl);
  console.log('[UpSPA] account_id =', body.get('account_id'));
  console.log('[UpSPA] posted old length =', body.get('old_password')?.length ?? 0);
  console.log('[UpSPA] posted new length =', body.get('new_password')?.length ?? 0);

  const resp = await fetch(actionUrl, {
    method,
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
    },
    body,
    credentials: 'include',
  });

  const html = await resp.text();

  if (!resp.ok) {
    console.warn('[UpSPA] secret-update rejected by login server:', resp.status, resp.statusText);
    document.open();
    document.write(html);
    document.close();
    return;
  }

  console.log('[UpSPA] login server accepted secret-update; committing to SPs');
  await commitSecretUpdateForSite(prepared);
  console.log('[UpSPA] secret-update committed to SPs');

  document.open();
  document.write(html);
  document.close();
}
document.addEventListener(
  'submit',
  (event) => {
    const form = event.target;
    if (!(form instanceof HTMLFormElement)) return;

    if (bypassForms.has(form)) {
      bypassForms.delete(form);
      return;
    }

    const pwds = getPasswordInputs(form);
    const flow = detectFlow(form, pwds);

    if (!flow) return;

    event.preventDefault();
    event.stopImmediatePropagation();

    (async () => {
      try {
        if (flow === 'register') {
          await handleRegister(form, pwds);
        } else if (flow === 'auth') {
          await handleAuth(form, pwds);
        } else {
          await handleSecretUpdate(form, pwds);
        }
      } catch (e) {
        const msg = explainError(e);
        console.error('[UpSPA] form handling failed:', e);
        alert(`UpSPA failed: ${msg}\n\nThe original password was NOT submitted.`);
      }
    })();
  },
  true,
);

console.log('[UpSPA] content script active:', window.location.origin);

fillMainUidInputs().catch((e) => console.warn('[UpSPA] UID autofill failed:', e));
document.addEventListener('DOMContentLoaded', () => {
  fillMainUidInputs().catch((e) => console.warn('[UpSPA] UID autofill failed:', e));
});
