CREATE DATABASE upspa1 OWNER upspa;
CREATE DATABASE upspa2 OWNER upspa;
CREATE DATABASE upspa3 OWNER upspa;
GRANT ALL PRIVILEGES ON DATABASE upspa1 TO upspa;
GRANT ALL PRIVILEGES ON DATABASE upspa2 TO upspa;
GRANT ALL PRIVILEGES ON DATABASE upspa3 TO upspa;
